### PR TITLE
[RHICOMPL-897] Hide global filter on all compliance screens

### PR DESCRIPTION
**Pull request by karelhala**
https://projects.engineering.redhat.com/browse/RHICOMPL-897

### CODE REVIEW

**Comment by karelhala** [comment]
ping @bastilian @akofink

**Review by AllenBW — APPROVED** [review]
That'll do it

**Review by akofink — APPROVED** [review]
Thanks!

**Comment by sthirugn** [comment]
@karelhala for my understanding, what is the reason behind this change?

**Pull request merged**
