### PR TITLE
Inv compliance v3

### PR DESCRIPTION
**Pull request by Hyperkid123**
Wait for v3 stable release of inventory compliance dependency.

cc @bastilian @vkrizan 
### Changes
- update FEC dependencies to v3
- removed module transpilations in test env (all except pf-icons)

### Results
- module size of all FEC dependencies in production went down from 274KB to 142KB (almost 50%)
- Production build time (my machine) is now around 50s
- Test run takes around 20s
- dev server rebuild takes around 3s

#### Tests times
```bash
Test Suites: 55 passed, 55 total
Tests:       159 passed, 159 total
Snapshots:   142 passed, 142 total
Time:        20.042 s
```

#### Prod build
```bash
webpack 5.17.0 compiled with 8 warnings in 47157 ms
```

#### Module size reduction (see tooltips)
**before**
Screenshot from 2021-01-29 11-28-36

**after**
Screenshot from 2021-01-29 11-28-25

### CODE REVIEW

**Comment by vkrizan** [comment]
Thank you @Hyperkid123, this is awesome!

**Comment by bastilian** [comment]
Thank you @Hyperkid123! I've skimmed through it all seems good, except for some CSS issues that you mentioned could occur. Do you want me to go over those? For now I think we can just inline the missing/overridden styles or do you have another solution to not loose them.

The most obvious examples are pagination on the SCAP Policies page for example. Or missing colours on icons.

**Comment by Hyperkid123** [comment]
@bastilian I will fix them. We are probably missing the top-level class on some element.

**Comment by Hyperkid123** [comment]
@bastilian ok, the icons are fixed. I also compared the pagination you have mentioned with ci.beta build but I didn't notice any difference. Could you share a right/wrong screenshot?

**Comment by bastilian** [comment]
@Hyperkid123 The colors are back! \o/ Thank you! Only some CSS issues left.

Here is what I see for the pagination on the rules table on a system details page: The pagination should actually be right aligned, like the bottom pagination in the Footer.

Screenshot 2021-02-01 at 14 01 33

There also seems to be an issue with our 404 pages, these use the InvalidObject component from frontend-components and seems to be missing some styling as well: 

Screenshot 2021-02-01 at 14 00 17

**Comment by Hyperkid123** [comment]
Hmm, the pagination is a strange one. I can't seem to be able to access my local node modules to test it :D What a day.

**Comment by Hyperkid123** [comment]
OK I know what is the problem. In the frontend components package we are import certain CSS files at the wrong places and webpack tree shakes them away. :palm_tree:

Working on a fix.

**Comment by Hyperkid123** [comment]
@bastilian ok, the styling issues are fixed. These are screenshots from the prod version of the build run locally.
screenshot-ci foo redhat com_1337-2021 02 04-09_25_55

screenshot-ci foo redhat com_1337-2021 02 04-09_26_06

**Review by bastilian — APPROVED** [review]
Thank you @Hyperkid123! Looks all good to me now!

**Comment by Hyperkid123** [comment]
@bastilian nice. I will create a stable release and update the version before mergning.

**Comment by Hyperkid123** [comment]
@bastilian the PR is ready.

**Pull request merged**
