### PR TITLE
revert(remediate): RHICOMPL-3002 fall back to remediationAvailable

### PR DESCRIPTION
**Pull request by skateman**
This reverts commit 0132ed16b91e63cee2cda2145f184f6b33a4a9a8.

## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [x] Input Validation
- [x] Output Encoding
- [x] Authentication and Password Management
- [x] Session Management
- [x] Access Control
- [x] Cryptographic Practices
- [x] Error Handling and Logging
- [x] Data Protection
- [x] Communication Security
- [x] System Configuration
- [x] Database Security
- [x] File Management
- [x] Memory Management
- [x] General Coding Practices

### CODE REVIEW

**Comment by bastilian** [comment]
@skateman Can we make a change so it works with both?

**Comment by bastilian** [comment]
@skateman It shouldn't be too much rewriting to to check wether or not the rule has an issueId and actually fallback to the manually constructed work, or?

**Comment by skateman** [comment]
I created a [followup card](https://issues.redhat.com/browse/RHICOMPL-3003) for that, would like to fix this ASAP.

**Review by bastilian — APPROVED** [review]
LGTM! Thank you @skateman!

**Pull request merged**
