### PR TITLE
build: enable logger in development

### PR DESCRIPTION
**Pull request by vkrizan**
after upgrade to Chrome 2.0

## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [X] Input Validation
- [X] Output Encoding
- [X] Authentication and Password Management
- [X] Session Management
- [X] Access Control
- [X] Cryptographic Practices
- [X] Error Handling and Logging
- [X] Data Protection
- [X] Communication Security
- [X] System Configuration
- [X] Database Security
- [X] File Management
- [X] Memory Management
- [X] General Coding Practices

### CODE REVIEW

**Review by akofink — APPROVED** [review]
Thanks!

**Comment by bastilian** [comment]
@vkrizan Have you checked if this is supposed to be disabled in the shared config? Sourcemaps was not supposed to be disabled, maybe this one should actually be enabled and this is an issue in the shared webpack config?

**Review by bastilian — APPROVED** [review]
Yes, supposed to be. just wanted to be sure. :)

**Comment by vkrizan** [comment]
This should on change the entry to the component that has the logger attached. The default is here https://github.com/RedHatInsights/frontend-components/blob/1e0c1916d6585c6f5361b8185e354693e02096e3/packages/config/federated-modules.js#L73

**Pull request merged**
