### PR TITLE
fix(Wizard): Add catch all in case response is incorrect

### PR DESCRIPTION
**Pull request by bastilian**

### CODE REVIEW

**Review by akofink — APPROVED** [review]
Thanks!

**Review by vkrizan — APPROVED** [review]
Looks good.

**Comment by akofink** [comment]
@bastilian any reason we shouldn't merge this?

**Comment by bastilian** [comment]
@akofink This was only a "quick fix", i'm not sure it this is the right solution as it is not tested well, but there is no reason to work on it more and ensure users always see a "nice" error message.

**Comment by akofink** [comment]
Even if it's not tested well, the solution seems straightforward and shouldn't do any harm. IMO we should merge it and revisit a better solution later, or if it's no longer an issue (I don't think that's the case?), we can close this PR altogether.

**Comment by vkrizan** [comment]
It's good enough to be merged, TBH. It does some small improvement.

**Pull request closed without merging**
