### PR TITLE
fix(ComplianceDetails): RHINENG-8348 fix perms in inventory

### PR DESCRIPTION
**Pull request by xmicha82**
## Steps to test
1. Log in as org admin
2. go to inventory and open a systems which is not assigned to any compliance policy
3. go to compliance tab
4. the Create new policy button should be enabled

## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [x] General Coding Practices

### CODE REVIEW

**Comment by mkholjuraev** [comment]
@xmicha82 can you please write a short description and how to test the PR? This would help reviewers to understand and test the issue better.

**Comment by xmicha82** [comment]
@mkholjuraev steps to reproduce are in the ticket, so i didn't think they were necessary in the PR, but i can surely include them if it's easier that way

**Review by mkholjuraev — APPROVED** [review]
LGTM! tested by running with the inventory app, I could see the button enabled for systems that are not assigned to any policy.

**Pull request merged**
