### PR TITLE
refactor: RHICOMPL-2894 replace majorOsVersion with osMajorVersion

### PR DESCRIPTION
**Pull request by skateman**
## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [x] General Coding Practices

### CODE REVIEW

**Review by vkrizan — APPROVED** [review]
Code changes looks good to me. Needs through testing of all pages.

**Comment by skateman** [comment]
@leSamo can you please take a look at this as well?

**Review by leSamo — APPROVED** [review]
I didn't find any regressions.

But filtering by major OS version does not work correctly, if I select RHEL 7 major version I receive no system even though I should, but this was the case even before this PR
rhel7

Without filter:
osfilter

**Comment by skateman** [comment]
@xmicha82 is the bug @leSamo describing the same as you're working on?

**Comment by xmicha82** [comment]
> @xmicha82 is the bug @leSamo describing the same as you're working on?

@skateman yes, this seems to part of the issue i am trying to solve

**Pull request merged**
