### PR TITLE
Openshift scanning first wizard step

### PR DESCRIPTION
**Pull request by dLobatog**
We may have this in beta, step by step, and only promote to stable by cherrypicking, thoughts @akofink? This will be a very large change if I have to include everything at once:

screenshot from 2019-03-04 18-07-34
screenshot from 2019-03-05 09-51-46
screenshot from 2019-03-05 09-51-56
screenshot from 2019-03-05 09-52-07

@katierik

### CODE REVIEW

**Comment by katierik** [comment]
Empty state: https://redhat.invisionapp.com/d/main#/console/16876256/349896817/preview
Connecting: https://redhat.invisionapp.com/d/main#/console/16876256/349896816/preview

Right now in the mocks, the connection is configured via a modal. 

There is also a step to associate a policy/profile with the imagestreams.
[Comment away on the mocks!]

**Comment by katierik** [comment]
Based on feedback from you, @akofink and Mohit, [the designs changed a bit](https://redhat.invisionapp.com/share/T4QSNP12WXK#/349896816_Add_An_Image_Stream). I'll let Mohit make the call on when that change should be built out. 

Re: the tab being visible to customers outside Red Hat: This worries me a bit, since we're not sure that we want to end up with a separate tab for image streams. 
Beyond that, the empty state should align closest with the ["not entitled" empty state](https://redhat.invisionapp.com/share/V8PLHRR6FAY#/355825641_Empty_State_-_Not_Entitled), but with some different copy. I don't see a screenshot of that here and since I've got a redhat email not sure how to see it - so not sure what is there now.

**Comment by dLobatog** [comment]
@akofink according to PM's feedback on the Slack channel, I'll hide the tab for the time being

**Comment by akofink** [comment]
In that case, there's not much danger in merging! :)

**Pull request merged**
