### PR TITLE
fix(PoliciesTable): business objective sorting

### PR DESCRIPTION
**Pull request by AsToNlele**
While making factory tests for policies, I noticed the business objective sorting is wrong.
When business objective is empty it's `null`. Javascript would assume it's a string value `null`. This breaks the sorting.

~~According to [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#description), Javascript sorts the values by UTF-16 code.~~

~~So this fix replaces the null value with the last UTF-16 character.~~

Empty business objectives will now be ahead of named ones.
image

### How to test:
1. Open `CompliancePolicies.js`
2. Use this code:
```js
  let { error, loading, refetch } = useQuery(QUERY);
  useEffect(() => {
    refetch();
  }, [location, refetch]);
  let policies;

  const data = {
    profiles: {
      edges: [
        {
          node: {
            id: 'asd',
            name: 'policy 1',
            description: 'desc',
            refId: 'xccdf',
            complianceThreshold: 51,
            totalHostCount: 10,
            osMajorVersion: '7',
            policyType: 'policy 1',
            policy: {
              id: 'asd',
              name: 'policy 1',
            },
            businessObjective: {
              title: 'moo',
            },
          },
        },
        {
          node: {
            id: 'asd',
            name: 'policy 2',
            description: 'desc',
            refId: 'xccdf',
            complianceThreshold: 51,
            totalHostCount: 10,
            osMajorVersion: '7',
            policyType: 'policy 2',
            policy: {
              id: 'asd',
              name: 'policy 1',
            },
            businessObjective: {
              title: 'aaa',
            },
          },
        },
        {
          node: {
            id: 'asd',
            name: 'policy 3',
            description: 'desc',
            refId: 'xccdf',
            complianceThreshold: 51,
            totalHostCount: 10,
            osMajorVersion: '7',
            policyType: 'policy 3',
            policy: {
              id: 'asd',
              name: 'policy 1',
            },
            businessObjective: null,
          },
        },
        {
          node: {
            id: 'asd',
            name: 'policy 4',
            description: 'desc',
            refId: 'xccdf',
            complianceThreshold: 51,
            totalHostCount: 10,
            osMajorVersion: '7',
            policyType: 'policy 3',
            policy: {
              id: 'asd',
              name: 'policy 1',
            },
            businessObjective: {
              title: 'zzzz',
            },
          },
        },
      ],
    },
  };
```
3. Test with the fix and verify the sorting is correct.

## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [x] General Coding Practices

### CODE REVIEW

**Comment by LightOfHeaven1994** [comment]
@AsToNlele nice catch :heart:

**Comment by mkholjuraev** [comment]
In such cases, shouldn't we change the API to return an empty string? There may be other places where this causes problems.

**Comment by AsToNlele** [comment]
@mkholjuraev an empty string precedes them all 
image

**Comment by bastilian** [comment]
@AsToNlele @mkholjuraev Defaulting to an empty string should be enough. And in my opinion that we use an empty string, which is sorted before "A" seems correcter. Like, 0,1,2,3 and not 1,2,3,0.

**Review by mkholjuraev — APPROVED** [review]
LGTM!

**Pull request merged**
