### PR TITLE
feat(tailoring): RHICOMPL-3433 swap associateRules to tailorProfile

### PR DESCRIPTION
**Pull request by skateman**
Should not affect anything, just a semantical change for now.

## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [x] General Coding Practices

### CODE REVIEW

**Comment by skateman** [comment]
@LightOfHeaven1994 this needs some adjustments to IQE tests :wink:

**Comment by LightOfHeaven1994** [comment]
@skateman thanks for letting know

**Comment by LightOfHeaven1994** [comment]
@skateman query `tailorProfile` fails for me with `"Parameter missing: param is missing or the value is empty: Missing argument identifying rule_groups"`

**Comment by skateman** [comment]
> @skateman query `tailorProfile` fails for me with `"Parameter missing: param is missing or the value is empty: Missing argument identifying rule_groups"`

Can you please create a jira bug for this? Ideally with steps to reproduce :pray:

**Review by LightOfHeaven1994 — APPROVED** [review]
Works great!

**Review by xmicha82 — APPROVED** [review]
Looks good to me

**Pull request merged**
