### PR TITLE
feat(RHINENG-14272): Policies page - async table

### PR DESCRIPTION
**Pull request by AsToNlele**
[RHINENG-14272](https://issues.redhat.com/browse/RHINENG-14272)

All should be fixed.

I've reused the useReportsExport hook, moved it to AsyncTableTools and now both the Reports page and Policies page use it.

## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [x] General Coding Practices

### CODE REVIEW

**Review by LightOfHeaven1994 — COMMENTED** [review]
Tested functionality locally and this is what I found:

1. Policy action column is missing (edit/delete kebab dropdown)
2. As you mentioned about loading state, also we probably don't need to do a reuqest with limit=1 to check if there are some policies. We can keep table in loading state until we get usual response with limit=10 and then show data or empty view depending on response.

1st issue needs to be fixed while 2nd one might be done as follow up later after release.

**Comment by AsToNlele** [comment]
1. Forgot about the kebab menu, will fix.

2. I'm afraid the request is needed. If we would request data, which don't exist (text filter = blablalbla), then the `total` would be 0 and a zero state would be shown.

**Comment by LightOfHeaven1994** [comment]
> 2\. would

oh right, we have a special zero state there and we need to show it appropriately! nice catch!

**Review by LightOfHeaven1994 — APPROVED** [review]
@AsToNlele amazing work! Loading table works perfectly!

**Pull request merged**
