### PR TITLE
fix(useExpandable): RHICOMPL-1555 - Set fullwidth as default

### PR DESCRIPTION
**Pull request by bastilian**
Screenshot 2021-08-19 at 14 35 22

Screenshot 2021-08-19 at 14 33 32

## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

### CODE REVIEW

**Comment by bastilian** [comment]
@katierik Mind taking a look at the screenshots. This makes the expanded pane full width and the distance from the border to the text edge ~22px, i'm not sure if the 24px mentioned in the Jira do also include the 2px border. Does it?

**Comment by katierik** [comment]
This matches the PF implementation so 👍 
The 2px border is part of the 24px total.

**Review by akofink — APPROVED** [review]
:+1: lgtm, too. Are we waiting for something (draft PR)?

**Comment by bastilian** [comment]
@akofink Thanks for taking a look as well. Just wanted to make sure it is correct and keep it in draft in case there would have been any more changes required.

**Pull request merged**
