### PR TITLE
Improve build performance

### PR DESCRIPTION
**Pull request by Hyperkid123**
### Changes
- transform FEC imports to use ESM build
- update webpack config and disable hashes in dev build

cc @bastilian

### CODE REVIEW

**Comment by bastilian** [comment]
@Hyperkid123 Thank you! This does improve the build time! However it still has the issue of returning 404 after another re-compile. I was able to reproduce the issue on two machines.

The issue seems to be around the file hashes option. When hashes are enabled all seems to work as expected, but the build time increases again and "Loading chunk" errors occur more often.

**Comment by bastilian** [comment]
Just in case we are not able to determine what the issue is that causes `webpack-dev-server` to throw 404s, the other changes still somewhat improve build times and iv v3 will even further improve it, we might be good.
It would still have the Load chunk errors, but that's better than the dev server not working properly at all. :D

**Review by akofink — COMMENTED** [review]
I was also able to reproduce the 404 issue after changing a file in devel.

**Comment by Hyperkid123** [comment]
@bastilian I will look at the issue with hashes. Disabling the chunk mapper in dev env might work. I think it has to go hand in hand with unhashed files.

**Comment by bastilian** [comment]
@Hyperkid123 That would be amazing! Thank you! There is no rush though, for now it seems to work. I did see the 404 with hashes enabled, but just once for now, and only after a longer while with multiple compiles in between. really odd issue.

**Comment by Hyperkid123** [comment]
@bastilian I see what is the issue. For some reason, after the webpack rebuild, the HTML template is just deleted. That is why we see the 404. There is no HTML to get. Hopefully, there will be a simple solution to this.

**Comment by Hyperkid123** [comment]
So the HTML template is held in webpack memory, but we serve it from a disk. We need to find a way to keep it there between rebuilds.

**Comment by bastilian** [comment]
> ok we are trolled by the CleanWebpackPlugin.

@Hyperkid123 OH! Nice catch! :)

**Comment by Hyperkid123** [comment]
@bastilian @akofink it should be working now. Even without hashes. The issue was the following.

Normally on asset rebuild, the index.html would rebuild, because the bundle hash has changed, therefore the HTML template had to be rebuild. But when we removed the hash changes, we no longer need to rebuild the HTML file and it is marked as `stale`. And the webpack clean plugin is removing stale assets. I've added an option to the webpack config file to preserve stale assets so the file is no longer removed after some source file change. It should also resolve the issues with missing chunks. I suspect it had the same problem. Sometimes chunks are not rebuilding and their hashes are not changed so they are stale.

**Comment by bastilian** [comment]
@Hyperkid123 Nice! Compile times are around ~40k ms for the initial compile and about half that on following compiles. 

I'll keep testing it throughout today while working and will merge later.

**Review by akofink — APPROVED** [review]
Seems to work fine for me, too. Seeing ~35s initial build time, ~4s after making a change.

**Pull request merged**
