### PR TITLE
update docs urls for Insights, Console, Cost & Subscriptions

### PR DESCRIPTION
**Pull request by ryandeussing**
## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

### CODE REVIEW

**Comment by LightOfHeaven1994** [comment]
@ryandeussing do you know when new links are going to work? We will need also to update our notifications template to point on 2023 instead of doc from 2021 https://github.com/RedHatInsights/notifications-backend/blob/master/engine/src/main/resources/templates/Compliance/complianceBelowThresholdEmailBodyV2.html#L14 here

**Review by LightOfHeaven1994 — APPROVED** [review]
lgtm

**Comment by LightOfHeaven1994** [comment]
@ryandeussing could you rebase your PR please? There was something with the jenkins so tests were not run. I hope it's going to be fixed with another push

**Comment by LightOfHeaven1994** [comment]
Closing in favour of https://github.com/RedHatInsights/compliance-frontend/pull/1905

**Comment by ryandeussing** [comment]
Thank you and apologies for the radio silence!

**Pull request closed without merging**
