### PR TITLE
Bump @patternfly & @redhat-cloud-services dependencies

### PR DESCRIPTION
**Pull request by bastilian**

### CODE REVIEW

**Review by katerinapat — COMMENTED** [review]
ah it looks it can't find `classnames`. A workaround that could fix it

install `classnames`  `npm install classnames`
and then added it as mapper
```
"moduleNameMapper": {
      ...
      "classnames": "<rootDir>/node_modules/classnames/index.js"
    }
```

**Comment by bastilian** [comment]
@katerinapat Thank you, that worked nicely! Tests/Travis are now 🟢! \o/

**Comment by bastilian** [comment]
@akofink Thank you for reviewing/testing, but mind taking (another) look. I also bumped the @redhat-cloud-services dependencies, for convenience, since Jenkins isn't cooperating and the merge/rebase scenarios would probably stress it more...

I tested it and it looks all fine, but would appreciate another set of eyes to approve.

**Review by akofink — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
