### PR TITLE
feat(test): add cypress tests

### PR DESCRIPTION
**Pull request by Fewwy**
Adding cypress testing library to the project. So anyone could write cypress tests when they need to
## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

### CODE REVIEW

**Comment by LightOfHeaven1994** [comment]
@Fewwy if you are curious why ci.int job fails - there is an issue with opening insights page in ephemeral env. Probably related to rone of the recent change  (not Compliance change). I asked people to take a look

**Comment by Fewwy** [comment]
@bastilian Have you ever encountered this error with commitlint? You can see it in the tests runner github action

**Comment by bastilian** [comment]
@Fewwy Sorry, no, I have never seen this issue before. :/

**Comment by Fewwy** [comment]
@gkarat I gave the lint back to the Travis and it's working now. Please approve the PR so we can merge it

**Review by gkarat — APPROVED** [review]
lgtm. let's keep everything in travis for now. I gonna merge it once the CI is complete

**Pull request merged**
