### PR TITLE
feat(PoliciesTable): RHICOMPL-2336 - Enable CSV/JSON export

### PR DESCRIPTION
**Pull request by bastilian**
Adds export functions to the policies table columns to enable export.

**How to test**

1. Visit the SCAP Policies page
2. Export the full set of polices
3. Add a random filter to limit the set of polices and export
4. Select specific policies and export

## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [x] General Coding Practices

### CODE REVIEW

**Review by vkrizan — COMMENTED** [review]
Code LGTM. Not tested.

**Comment by skateman** [comment]
@bastilian the export button is not really intuitive here, it took me some time to find it. Maybe we could create a followup issue regarding that. Otherwise it looks good!

**Review by skateman — APPROVED** [review]
The Seal of Approval

**Comment by bastilian** [comment]
> Maybe we could create a followup issue regarding that. Otherwise it looks good!

Nothing we can do about that. This is a "platform standard" that applies to all tables.

**Pull request merged**
