### PR TITLE
Update patternfly deps for new FEC

### PR DESCRIPTION
**Pull request by dLobatog**
After https://github.com/RedHatInsights/compliance-frontend/commit/bbd907e772f234cfe376cb0ad71e55f4fd862805 , if you run the following command, you will notice the peer deps for patternfly are not the right ones for many of our deps. This caused the remediations dialog to show up wrong, alongside other UX issues on CI. 

Screenshot from 2019-05-20 11-03-57

This PR fixes that by updating the patternfly peer deps.  

```
npm ls --depth=0 --json
{
  "name": "compliance-frontend",
  "version": "1.1.0",
  "problems": [
    "peer dep missing: @babel/core@>=7.0.0-beta.50 <7.0.0-rc.0, required by @babel/preset-es2017@7.0.0-beta.53",
    "peer dep missing: @patternfly/react-core@^3.2.6, required by @redhat-cloud-services/frontend-components@0.0.5",
    "peer dep missing: @patternfly/react-core@^3.2.6, required by @redhat-cloud-services/frontend-components-inventory-compliance@0.0.2",
    "peer dep missing: @patternfly/react-core@^3.2.6, required by @redhat-cloud-services/frontend-components-notifications@0.0.3",
    "peer dep missing: @patternfly/react-core@^3.2.6, required by @redhat-cloud-services/frontend-components-remediations@0.0.3",
    "peer dep missing: @patternfly/react-core@^3.2.6, required by @redhat-cloud-services/frontend-components-utilities@0.0.5",
    "peer dep missing: @patternfly/react-icons@^3.7.4, required by @redhat-cloud-services/frontend-components@0.0.5",
    "peer dep missing: @patternfly/react-icons@^3.7.4, required by @redhat-cloud-services/frontend-components-inventory-compliance@0.0.2",
    "peer dep missing: @patternfly/react-icons@^3.7.4, required by @redhat-cloud-services/frontend-components-notifications@0.0.3",
    "peer dep missing: @patternfly/react-icons@^3.7.4, required by @redhat-cloud-services/frontend-components-remediations@0.0.3",
    "peer dep missing: @patternfly/react-table@^2.1.6, required by @redhat-cloud-services/frontend-components-inventory-compliance@0.0.2",
    "peer dep missing: @patternfly/react-table@^2.1.6, required by @redhat-cloud-services/frontend-components-remediations@0.0.3",
    "peer dep missing: react@^16.5.1, required by @redhat-cloud-services/frontend-components@0.0.5",
    "peer dep missing: react@^16.5.1, required by @redhat-cloud-services/frontend-components-inventory-compliance@0.0.2",
    "peer dep missing: react@^16.5.1, required by @redhat-cloud-services/frontend-components-notifications@0.0.3",
    "peer dep missing: react@^16.5.1, required by @redhat-cloud-services/frontend-components-remediations@0.0.3",
    "peer dep missing: react@^16.5.1, required by @redhat-cloud-services/frontend-components-utilities@0.0.5",
    "peer dep missing: react-content-loader@^3.4.1, required by @redhat-cloud-services/frontend-components@0.0.5",
    "peer dep missing: react-content-loader@^3.4.1, required by @redhat-cloud-services/frontend-components-inventory-compliance@0.0.2",
    "peer dep missing: react-dom@^16.5.1, required by @redhat-cloud-services/frontend-components@0.0.5",
    "peer dep missing: react-dom@^16.5.1, required by @redhat-cloud-services/frontend-components-inventory-compliance@0.0.2",
    "peer dep missing: react-dom@^16.5.1, required by @redhat-cloud-services/frontend-components-notifications@0.0.3",
    "peer dep missing: react-dom@^16.5.1, required by @redhat-cloud-services/frontend-components-remediations@0.0.3",
    "peer dep missing: react-dom@^16.5.1, required by @redhat-cloud-services/frontend-components-utilities@0.0.5",
    "peer dep missing: react-redux@^6.0.0, required by redux-form@8.1.0"
  ],
```

### CODE REVIEW

**Comment by dLobatog** [comment]
@akofink Let me fix react-content-loader - the other 2 are problematic, react-redux 6.0.0 requires more changes than just updating the version and I'm not sure if we even need babel/preset-es2017

**Comment by dLobatog** [comment]
@akofink Updated!

**Comment by akofink** [comment]
Are you seeing weirdness with the tabs?

image

**Comment by dLobatog** [comment]
@akofink I am not currently seeing that, can you `rm -r node_modules`?
Peek 2019-05-21 15-25

**Pull request merged**
