### PR TITLE
feat(Policies): RHICOMPL-3768 - Request additional rule data separately

### PR DESCRIPTION
**Pull request by bastilian**
This changes the requesting of additional data, like the rule tree and value definitions with values for rules of policies/profiles to be requested only when needed and separately.

**How to test:**

1) Verify that the rules table behaves correctly with both ruleGroups and valueEditing disabled (append `?ruleGroups=disable` and `?valueEditing=disable` to the URL of any page containing a rules table.
2) Enable (append `?ruleGroups=enable` and `?valueEditing=enable`) both or only one feature and verify rules tables in the Crate Policy wizard, on the Policy Details, in the Edit Policy/Rules modal and on the Systems Details page work properly and allow using the new features. 

## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [x] General Coding Practices

### CODE REVIEW

**Review by gkarat — COMMENTED** [review]
I get "something went wrong" when navigating to the SCAP Policies details page and selecting the Rules tab:
```
_profileWithRules$val.filter is not a function
```

Also, please correct me if I am wrong, but does the Systems details (/systems/%id) page contain the rules table? If so, I couldn't apply the URL parameters you listed in How to test. They are erased when the page is loaded and have no effect.

**Comment by bastilian** [comment]
@gkarat Please test https://github.com/RedHatInsights/compliance-frontend/pull/1946 It contains this PR as well as a fix for the issue you were encountering.

Regarding the feature flags: It is meant to redirect you back to a the page without the parameter to set the feature flag. I also assume that due to the error it might have not gone through properly. You can verify if the flag was correctly set in local storage:


Screenshot 2023-06-20 at 13 06 09

**Comment by gkarat** [comment]
Thank you. Does it make sense then to close this PR?

**Comment by bastilian** [comment]
Included in https://github.com/RedHatInsights/compliance-frontend/pull/1946

**Pull request closed without merging**
