### PR TITLE
feat(RHIN-830): Add Zero State to Compliance

### PR DESCRIPTION
**Pull request by adonispuente**
As in accordance to these mocks, this PR adds zero state to compliance,  https://docs.google.com/document/d/1FGuzbL2jyRmn_coYD5Z_o3d0MhOf1vQDT46NQvsfPyA/edit#heading=h.1hvxoje16w3i  https://www.sketch.com/s/550bd962-ca1f-42d8-8d89-d457527a059a/a/qbe9Ol2#Inspect   https://www.sketch.com/s/550bd962-ca1f-42d8-8d89-d457527a059a/prototype/a/AEF47CA9-8F00-40FC-B39B-3B989D3F83FD

### CODE REVIEW

**Comment by adonispuente** [comment]
Test are passing locally. Not sure why ci is failing yet

**Comment by bastilian** [comment]
> Test are passing locally. Not sure why ci is failing yet

Try `npm run lint` ;)

**Review by bastilian — APPROVED** [review]
@adonispuente LGTM on beta/preview, but on non beta this would cause an error until the dashboard is deployed to stable with the zero state.

**Comment by adonispuente** [comment]
@bastilian with npm run lint it still passes locally.

**Pull request merged**
