### PR TITLE
fix(CreatePolicy): RHICOMPL-1864 crash on type re-selection

### PR DESCRIPTION
**Pull request by vkrizan**
after the Rules step was already drawn.

Fixes:
```
TypeError: prevSelection is null
    additionalSelection ruleSelection.js:18
    profilesWithRulesToSelection ruleSelection.js:17
    EditPolicyProfilesRules EditPolicyProfilesRules.js:154
    React 6
react_devtools_backend.js:2560:23
```

## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [X] Input Validation
- [X] Output Encoding
- [X] Authentication and Password Management
- [X] Session Management
- [X] Access Control
- [X] Cryptographic Practices
- [X] Error Handling and Logging
- [X] Data Protection
- [X] Communication Security
- [X] System Configuration
- [X] Database Security
- [X] File Management
- [X] Memory Management
- [X] General Coding Practices

### CODE REVIEW

**Comment by bastilian** [comment]
There still seems to be an issue when only the benchmark changes.

The following scenario crashes with `TypeError: can't access property "find", t is null` in CI with this patch applied it doesn't crash, but also doesn't show any rules: 


https://user-images.githubusercontent.com/7757/119501575-444c5100-bd69-11eb-8f06-af4654aa88f9.mp4

**Comment by vkrizan** [comment]
@bastilian I unable to reproduce it. I see the bulk select in the video. Did you cherry-picked it to your new changes?

**Review by akofink — APPROVED** [review]
Works as expected and fixes the error. Thanks!

**Review by bastilian — APPROVED** [review]
LGTM! Thanks @vkrizan!

> I see the bulk select in the video. Did you cherry-picked it to your new changes?

Yeah, this manifested an issue in the bulk select, which is fixed now too. I wanted to make sure the RulesTable changes still worked properly too with this.

**Pull request merged**
