### PR TITLE
fix(Reports): RHICOMPL-1302 - Fix banner title

### PR DESCRIPTION
**Pull request by sthirugn**

### CODE REVIEW

**Review by vkrizan — APPROVED** [review]
Thanks.

PS: You can also remove the space after equal sign.

**Comment by sthirugn** [comment]
sure, will update it

**Review by akofink — APPROVED** [review]

**Comment by sthirugn** [comment]
> PS: You can also remove the space after equal sign.

Done!

**Comment by sthirugn** [comment]
also if one of you can merge, it would be great, I don't have write acess.

**Pull request merged**
