### PR TITLE
chore: do not run commit-lint for pull-requests

### PR DESCRIPTION
**Pull request by mkholjuraev**
## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist

Do not run commit-lint in pull requests as it is in inventory.

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

### CODE REVIEW

**Comment by bastilian** [comment]
@mkholjuraev I don't see a reason for changing this.

**Comment by mkholjuraev** [comment]
The reason is that during the pull review process, the commit lint creates a lot of issues due to updating and maintaining the branch.

**Comment by bastilian** [comment]
@mkholjuraev We should also encourage the format in PR commit messages. So far this has worked in compliance without issue.

**Comment by mkholjuraev** [comment]
Let bring consistency between apps. I have created this PR by copy pasting it from inventory [PR](https://github.com/RedHatInsights/insights-inventory-frontend/pull/2197) :).

**Comment by mkholjuraev** [comment]
We agreed to make inventory consistent to run lint for both master and pull requests

**Pull request closed without merging**
