### PR TITLE
fix(Doc): RHICOMPL-3781 - Fix unsupported doc link

### PR DESCRIPTION
**Pull request by LightOfHeaven1994**
Fixing non-working link to point on Supported SSGs article

## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

### CODE REVIEW

**Review by vkrizan — APPROVED** [review]
LGTM

**Comment by Fewwy** [comment]
Fix is confirmed. Need to fix the ci.int and we can merge it

**Review by Fewwy — APPROVED** [review]

**Comment by LightOfHeaven1994** [comment]
PR check is going to fail until navigation fixed https://issues.redhat.com/browse/RHCLOUD-26185

**Pull request merged**
