### PR TITLE
chore: RHICOMPL-3522 - Upgrade to react router v6

### PR DESCRIPTION
**Pull request by bastilian**
Implements https://issues.redhat.com/browse/RHICOMPL-3522.

## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [x] General Coding Practices

### CODE REVIEW

**Review by adonispuente — COMMENTED** [review]
When bringing this down and testing locally everything seems to run fine, I can check again once test pass but once those are good I think this is good to go, great job!

**Comment by adonispuente** [comment]
Screen Shot 2023-06-28 at 6 17 10 PM
 I ran into an issue while testing on the qa account -> beta env. 
 When I click on a report, the url is incorrect, in the example in the picture the url I get is: 
 
 https://stage.foo.redhat.com:1337/preview/preview/insights/compliance/reports/49a3ebfc-c3f7-40b9-93e1-ea7b940c9b43
 where /preview appears twice 
 
 When testing in stable env everything works perfectly.

**Comment by bastilian** [comment]
@adonispuente Have you reinstalled the packages? This issue should have been resolved with a fix in the FEC packages.

**Comment by LightOfHeaven1994** [comment]
This is what i found so far:
If you have empty state on Reports/SCAPPolicies page - you will see no button "Create new policy" but <a>

image

**Comment by bastilian** [comment]
@LightOfHeaven1994 Thank you for testing and catching this! It's now a button again! :)

**Review by AsToNlele — APPROVED** [review]
Really good job, works great! LGTM :smile:

**Comment by LightOfHeaven1994** [comment]
@bastilian I found 1 more issue. If you open Edit policy/Delete policy from Scap Policies modal fails to load because link is wrong. There has to be `/insights/compliance/scappolicies/<ID>/edit` but I only see `/scappolicies/<ID>/edit`

[Screencast from 2023-07-07 09-27-29.webm](https://github.com/RedHatInsights/compliance-frontend/assets/33912805/a2c12bfc-b25b-48f4-9ca8-b19e3303ec66)

**Review by adonispuente — APPROVED** [review]
Works as intended, LGTM!

**Review by mkholjuraev — COMMENTED** [review]
I also faced issue on scap policies action modals.

**Comment by bastilian** [comment]
@LightOfHeaven1994 @mkholjuraev The issue with the actions on the SCAP policies page should be fixed with @gkarat's commit.

**Comment by LightOfHeaven1994** [comment]
@bastilian sure, I will take a look later today (I will also check why pipeline failed)

**Comment by LightOfHeaven1994** [comment]
@bastilian So test fails because we are checking Compliance empty views and Create policy button disappeared from there (screenshot made in ephemeral env but same issue if you run your PR against stage)

image


I also noticed different style for download pdf buttons, is it expected?
image (22)

**Comment by bastilian** [comment]
@LightOfHeaven1994 Thank you for the repeated testing! <3 The button to create policies is now back on the empty state and the download button is now plain again. :)

**Comment by LightOfHeaven1994** [comment]
@bastilian let's get it to stage so I can test it more. Thanks!

**Pull request merged**
