### PR TITLE
Adapt to ssg: remediations API format

### PR DESCRIPTION
**Pull request by dLobatog**
This should be completed with a similar PR in insights-frontend-components. This button is only used in the SystemsTable, but the `insights-frontend-components` one is used in the rules table.

### CODE REVIEW

**Comment by akofink** [comment]
This requires https://github.com/RedHatInsights/compliance-backend/pull/91, right?

**Comment by akofink** [comment]
So, to be clear, here's how I'm testing (is this right?):

1. In the compliance systems table
1. Check the box next to a host
1. Click the "Remediate with Ansible" button

I'm getting `TypeError: Issues array must not be empty` in the JS console.

**Comment by akofink** [comment]
@dLobatog what's going on with this one?

**Comment by dLobatog** [comment]
@akofink This one is unrelated to that though, this one is only fixing the button for our current `systems` table, click on a host and then "remediate with ansible" to check it

**Comment by dLobatog** [comment]
Here's a quick demo, after removing `node_components` here, and running `npm install` and `npm link ../insights-frontend-compliance`:

Peek 2019-05-01 20-53

Notice the FEC change was included in a previous PR which is deployed already to CI and doesn't show any weird icons: https://github.com/RedHatInsights/compliance-frontend/commit/43f9135ee62c1e948e96173877e81046879ce2f0

**Comment by dLobatog** [comment]
This now includes https://github.com/RedHatInsights/insights-frontend-components/pull/414

**Pull request merged**
