### PR TITLE
feat(CreatePolicy): RHICOMPL-1354 reorder steps 

### PR DESCRIPTION
**Pull request by vkrizan**
Swaps Rules and Systems steps, to start with Systems first.
Updated wording on the Systems steps according to mocks.

Screenshot_2021-03-10 SCAP policies - Compliance Red Hat Insights

## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [X] Input Validation
- [X] Output Encoding
- [X] Authentication and Password Management
- [X] Session Management
- [X] Access Control
- [X] Cryptographic Practices
- [X] Error Handling and Logging
- [X] Data Protection
- [X] Communication Security
- [X] System Configuration
- [X] Database Security
- [X] File Management
- [X] Memory Management
- [X] General Coding Practices

### CODE REVIEW

**Comment by skateman** [comment]
Code looks okay to me, is it enough to believe that the screenshot is true or should I test this manually?

**Comment by vkrizan** [comment]
@skateman please try to test it

**Review by skateman — APPROVED** [review]
The Seal of Approval

**Review by akofink — APPROVED** [review]
Works as expected. Thanks!

**Pull request merged**
