### PR TITLE
fix(RulesTable): RHICOMPL-3530 - Show Identifiers and Refs for rules

### PR DESCRIPTION
**Pull request by LightOfHeaven1994**
1) References and identifiers are shown now on both pages (System details and Policy details->Rules).
2) Fixed spacing between elements

**Before:**
image

**After:**
image

Also closing https://issues.redhat.com/browse/RHICOMPL-3165 here

## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

### CODE REVIEW

**Comment by mkholjuraev** [comment]
@LightOfHeaven1994 the code looks good. But I have not tried verifying it locally. Can you some steps to test it?

**Comment by LightOfHeaven1994** [comment]
@mkholjuraev Sure! You need to have a reported system (Policy + system with rule results).
1) Then navigate to System details to see RulesTable. Try to expand some rules to see if it looks correctly.
2) Navigate to SCAP Policies -> click on your policy and select Rules tab. Try to expand some rules to see if it looks correctly.

**Review by mkholjuraev — APPROVED** [review]
LGTM! workes as described. @LightOfHeaven1994 thanks!

**Pull request merged**
