### PR TITLE
fix(RHINENG-1917): Fix FinishedCreatePolicy error message

### PR DESCRIPTION
**Pull request by LightOfHeaven1994**
Minor fix of printing full error message

Before:
image

After:
image

## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

### CODE REVIEW

**Review by leSamo — COMMENTED** [review]
While we're at it, could we please fix the typo and rename `EmtpyStateWithErrors` component to `EmptyStateWithErrors` to avoid future problems? Thanks!

**Comment by LightOfHeaven1994** [comment]
> While we're at it, could we please fix the typo and rename `EmtpyStateWithErrors` component to `EmptyStateWithErrors` to avoid future problems? Thanks!

good catch, fixed

**Comment by xmicha82** [comment]
LGTM, thx @LightOfHeaven1994  👍🏻

**Review by xmicha82 — APPROVED** [review]

**Pull request merged**
