### PR TITLE
ci(autosync): RHICOMPL-3157 add branch sync and pr creation for stage

### PR DESCRIPTION
**Pull request by Victoremepunto**
This PR aims to achieve two things on push to `master` events:

 - Automatically merge changes from `master` to `qa-beta` (only FF)
 - Automatically create PR from `master` to `qa-stabe` 

## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [X] General Coding Practices

### CODE REVIEW

**Comment by Victoremepunto** [comment]
Great teamwork @LightOfHeaven1994  !!! 

@bastilian  - with :heart:  for you ;)

**Comment by skateman** [comment]
I ABSOLUTELY LOVE THIS :tada: :heart_eyes: but let's ask @bastilian if he's okay with it

**Comment by vkrizan** [comment]
Would this be needed with containerized frontends?

**Comment by Victoremepunto** [comment]
> Would this be needed with containerized frontends?

I would depend on what triggers the image creation and how the branches are required. 

It could happen that we only need to have `master` and just rely on container registry tags. 

This feature is more about the "annoying need" of manually updating branches - if we don't end up needing to do it , then I guess no :) 

@gburges  you happen to know if the branching strategy is expected to change with the containerized frontend strategy ?

**Comment by LightOfHeaven1994** [comment]
Even if it's for 1 month usage, it will be good to have it :)

**Comment by skateman** [comment]
> Even if it's for 1 month usage, it will be good to have it :)

Give this man a :1st_place_medal: and some :cookie: :cookie:

**Comment by vkrizan** [comment]
:ship: it

**Comment by gburges** [comment]
There will be single branch builds and feature flags afaik, @Blake Holifield
***@***.***> is closer to the fire, he might know more/who to talk
to ;)

**Review by bastilian — APPROVED** [review]
THANK YOU @Victoremepunto! <3

**Comment by Victoremepunto** [comment]
> THANK YOU @Victoremepunto! <3

Also thanks to @LightOfHeaven1994  !!

**Pull request merged**
