### PR TITLE
fix(supported popover): RHICOMPL-1461 update docs link

### PR DESCRIPTION
**Pull request by akofink**
It seems the url for this page changed slightly without us being notified. The link is defined in frontend components also, so I've opted to export it there. This PR required https://github.com/RedHatInsights/frontend-components/pull/992.

Signed-off-by: Andrew Kofink <akofink@redhat.com>

## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [X] Input Validation
- [X] Output Encoding
- [X] Authentication and Password Management
- [X] Session Management
- [X] Access Control
- [X] Cryptographic Practices
- [X] Error Handling and Logging
- [X] Data Protection
- [X] Communication Security
- [X] System Configuration
- [X] Database Security
- [X] File Management
- [X] Memory Management
- [X] General Coding Practices

### CODE REVIEW

**Review by sthirugn — APPROVED** [review]
lgtm

**Comment by akofink** [comment]
Sorry, @sthirugn - I realized the same link was in frontend components, so I've imported it from there now, but this PR now requires https://github.com/RedHatInsights/frontend-components/pull/992.

**Comment by sthirugn** [comment]
@akofink np, I will let @bastilian or @vkrizan review then :)

**Review by vkrizan — APPROVED** [review]
LGTM. Tried warning under the donut in Reports and the one on systems list.

**Pull request merged**
